Name - Sahildeep Singh

Roll No - 8025320084

Q1 Create a data file by using Python random module with different random generator parameters. The data file must have 20000 X 10000 (rows X columns) in the data file. This data file to be used as database for realization of math and matrix operations in cloud computing lab assignments.

In [ ]:
import numpy as np
rows = 20000
cols = 10000
# Integer random values (0 to 100)
data_integer = np.random.randint(0, 100, size=(rows, cols))
np.save("large_dataset.npy", data_integer)
print("Data file created")
print("Shape:", data_integer.shape)

Data file created
Shape: (20000, 10000)


Q2. Write a program in Python to assign subsequent rows to matrix first row elements.

In [ ]:

matrix = np.random.randint(1, 100, size=(5, 5))

print("Original Matrix:")
print(matrix)

# Step 2: Assign first row to all rows
matrix[:] = matrix[0]

# Step 3: Print updated matrix
print("\nUpdated Matrix (First row assigned to all rows):")
print(matrix)

Original Matrix:
[[78 83 37 38 56]
 [80 89 12 92 27]
 [47 55 82 69 20]
 [19 99 69 29 56]
 [53 45 59 16 23]]

Updated Matrix (First row assigned to all rows):
[[78 83 37 38 56]
 [78 83 37 38 56]
 [78 83 37 38 56]
 [78 83 37 38 56]
 [78 83 37 38 56]]


Q3. Write a program in Python to group similar elements into matrix.

In [ ]:
import numpy as np

data = np.random.randint(1, 6, size=20)

print("Original Data:")
print(data)

unique_values = np.unique(data)

matrix = []

for val in unique_values:
    group = data[data == val]
    matrix.append(group.tolist())

print("\nGrouped Matrix:")
for row in matrix:
    print(row)

Original Data:
[4 4 5 5 4 5 4 3 4 1 2 2 1 4 5 5 2 2 2 2]

Grouped Matrix:
[1, 1]
[2, 2, 2, 2, 2, 2]
[3]
[4, 4, 4, 4, 4, 4]
[5, 5, 5, 5, 5]


Q4. Write a program in Python to add and subtract matrices in python.

In [ ]:
import numpy as np

# Generate two random matrices
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

# Operations
add = A + B
sub = A - B

# Separate print statements (exactly 4)
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition (A + B):\n", add)
print("\nSubtraction (A - B):\n", sub)

Matrix A:
 [[2 3 8]
 [6 1 3]
 [2 3 8]]

Matrix B:
 [[9 6 2]
 [2 4 7]
 [2 2 1]]

Addition (A + B):
 [[11  9 10]
 [ 8  5 10]
 [ 4  5  9]]

Subtraction (A - B):
 [[-7 -3  6]
 [ 4 -3 -4]
 [ 0  1  7]]


Q5. Write a program in Python to create an n x n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.

In [ ]:
def create_even_corner_matrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i][j] = 2 * (i + j)
    return matrix

n = 4
matrix = create_even_corner_matrix(n)
print("Matrix:\n", matrix)

# Verify opposite corners of full matrix
print("\nTop-left corner:", matrix[0][0])
print("Bottom-right corner:", matrix[n-1][n-1])
print("Sum:", matrix[0][0] + matrix[n-1][n-1], "-> Even?", (matrix[0][0] + matrix[n-1][n-1]) % 2 == 0)

Matrix:
 [[ 0  2  4  6]
 [ 2  4  6  8]
 [ 4  6  8 10]
 [ 6  8 10 12]]

Top-left corner: 0
Bottom-right corner: 12
Sum: 12 -> Even? True


Q6 Write a program in Python to perform row-wise element addition in tuple matrix

In [ ]:
# Tuple matrix
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

# Row-wise addition
row_sums = tuple(sum(row) for row in matrix)

# Output
print("Tuple Matrix:", matrix)
print("Row-wise Sum:", row_sums)

Tuple Matrix: ((1, 2, 3), (4, 5, 6), (7, 8, 9))
Row-wise Sum: (6, 15, 24)
